help:
	@echo "    start"
	@echo "        start the bots"
	@echo "    debug"
	@echo "        start jupyter notebook for interactive debug"

.PHONY: start
start:
	@./scripts/start.sh

.PHONY: debug
debug:
	@jupyter notebook

